name: Generate README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 7/12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Update README
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB }}
      run: |-
        python run.py
        cat README.md
    - name: Commit and push if changed
      run: |-
        git diff
        git config --global user.email "JaxkDev@gmail.com"
        git config --global user.name "JaxkDev-Workflow"
        git add -A
        git commit -m "Generated README" || exit 0
        git push
